import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['**/*.{test,spec}.{ts,tsx}'],
    exclude: ['node_modules', 'dist', 'build', '.git'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      // Keep the gate focused on deterministic domain/data modules. UI shells,
      // generated assets, and browser-only integration code are covered by
      // higher-level checks and should not dilute this unit-test signal.
      include: [
        'src/app/commands/system/parser.ts',
        'src/app/commands/system/registry.ts',
        'src/app/commands/system/vimSequenceParser.ts',
        'src/app/core/data/normalizedStore.ts',
        'src/app/core/storage/localStorage.ts',
        'src/app/core/storage/adapters/MarkdownFileIO.ts',
        'src/app/features/markdown/markdownImporter.ts',
        'src/app/features/markdown/markdownExport.ts',
        'src/app/features/markdown/markdownLinkUtils.ts',
        'src/app/features/markdown/mindMeisterParser.ts',
        'src/app/features/markdown/markdownNodeMerge.ts',
        'src/app/features/markdown/utils/table-editor/tableParser.ts',
        'src/app/features/markdown/utils/table-editor/tableSerializer.ts',
        'src/app/features/markdown/utils/table-editor/tableValidation.ts',
        'src/app/features/markdown/utils/tableExtractor.ts',
        'src/app/features/mindmap/utils/mapSearch.ts',
        'src/app/features/mindmap/utils/nodeTraversal.ts',
        'src/app/features/mindmap/utils/nodeFunctional.ts',
        'src/app/features/mindmap/utils/nodeOperations.ts',
        'src/app/features/mindmap/utils/pasteTree.ts',
        'src/app/features/mindmap/utils/linkUtils.ts',
        'src/app/features/mindmap/services/MarkdownConversionService.ts',
        'src/app/features/mindmap/services/MapOperationsService.ts',
        'src/app/features/mindmap/services/PathResolutionService.ts',
        'src/app/features/vim/services/VimCountBuffer.ts',
        'src/app/features/vim/services/VimRepeatRegistry.ts',
        'src/app/shared/utils/fileSize.ts',
        'src/app/shared/utils/hashUtils.ts',
        'src/app/shared/utils/lineEndingUtils.ts',
        'src/app/shared/utils/mapUrl.ts',
        'src/app/shared/utils/pathOperations.ts',
        'src/app/shared/utils/safeJson.ts',
        'src/app/shared/utils/stringUtils.ts',
        'src/app/shared/utils/treeUtils.ts',
        'src/app/shared/utils/lruCache.ts',
        'src/app/commands/utils/commandFunctional.ts',
        'src/app/commands/utils/commandFactories.ts',
        'src/app/commands/utils/commandResults.ts',
      ],
      exclude: [
        'node_modules/',
        'src/test/',
        'dist/',
        'coverage/',
        'jscpd-report/',
        '**/*.d.ts',
        '**/*.config.*',
        '**/mockData',
        '**/*.test.{ts,tsx}',
        '**/*.spec.{ts,tsx}',
      ],
      thresholds: {
        lines: 70,
        functions: 70,
        branches: 70,
        statements: 70,
      },
    },
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
      '@shared': resolve(__dirname, './src/app/shared'),
      '@mindmap': resolve(__dirname, './src/app/features/mindmap'),
      '@core': resolve(__dirname, './src/app/core'),
      '@commands': resolve(__dirname, './src/app/commands'),
    },
  },
});
