name = "mindoodle-backend"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[env.production.vars]
ALLOWED_EMAIL = "shigekazukoya@gmail.com"

[[env.production.kv_namespaces]]
binding = "USERS"
id = "26ed643d1e894f3cae22e60b4e8cd566"

[[env.production.r2_buckets]]
binding = "MAPS_BUCKET"
bucket_name = "mindoodle-maps"

[env.development]
compatibility_date = "2024-10-01"

[env.development.vars]
ALLOWED_EMAIL = "shigekazukoya@gmail.com"

[[env.development.kv_namespaces]]
binding = "USERS"
id = "49eb2b709ef04f94a2550901c4df8631"

[[env.development.r2_buckets]]
binding = "MAPS_BUCKET"
bucket_name = "mindoodle-maps-dev"